[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
supergloo = { version = "0.2.3", path = "../supergloo" }
tokio = { version = "1.45.0", features = ["full"] }
