[package]
name = "supergloo"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3", features = ["macros", "tracing"] }
derive_more = { version = "2.0.1", features = ["full"] }
inventory = "0.3.20"
gloo_macros = { version = "0.1.0", path = "../macros", optional = true } 

[features]
macros = ["dep:gloo_macros"]
default = ["macros"]
